#1668 Fix subCriteria's not being updated
spring-projects/spring-data-elasticsearch pull request #1670
Opened 2021-01-27 15:40 UTC by slyoldfox

- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] There is a ticket in the bug tracker for the project in our [issue tracker](https://github.com/spring-projects/spring-data-elasticsearch/issues).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

2021-01-27 15:40 UTC, pivotal-issuemaster commented
@slyoldfox Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=1670)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=1670) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-01-28 19:35 UTC, sothawo requested changes
Thanks for this PR. It looks good, can you

* check and tick off the marks in the PR template (adding your name etc)
* sign the contributor's agreement
* rebase you branch on master an force push

the I can merge this

2021-01-28 19:35 UTC, sothawo commented on src/test/java/org/springframework/data/elasticsearch/core/CriteriaQueryMappingUnitTests.java
> +						.subCriteria( Criteria.where( "createdDate").is(calendar.getTime()) ) //
```suggestion
						.subCriteria( Criteria.where( "createdDate").is(383745721653L) ) //
```
no need for the `Calendar` stuff here (I'd not use the old `java.util` date classes anyway, but always the classes from `java.time`).

2021-01-28 19:35 UTC, sothawo commented on src/test/java/org/springframework/data/elasticsearch/core/CriteriaQueryMappingUnitTests.java
> +	// DATAES-1668
```suggestion
	// #1668
```
DATAES was when we were using Jira, now we just use the #NNN

2021-01-28 19:35 UTC, sothawo commented on src/test/java/org/springframework/data/elasticsearch/core/CriteriaQueryMappingUnitTests.java
> +		// DATAES-1668
```suggestion
		// #1668
```

2021-01-28 21:58 UTC, pivotal-issuemaster commented
@slyoldfox Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=1670)!

2021-01-28 22:24 UTC, slyoldfox commented
@sothawo Not a git wizard here - I hope I ticked off all the steps  as required :-)

2021-01-29 14:30 UTC, merged