Add Rescore functionality
spring-projects/spring-data-elasticsearch pull request #1688
Opened 2021-02-11 22:04 UTC by peermuellerxw

Closes #1686

- [ x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ x] There is a ticket in the bug tracker for the project in our [issue tracker](https://github.com/spring-projects/spring-data-elasticsearch/issues).
- [ x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ x] You submit test cases (unit or integration tests) that back your changes.
- [ x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

2021-02-11 22:04 UTC, pivotal-issuemaster commented
@peermuellerxw Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=1688)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=1688) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-02-11 22:09 UTC, pivotal-issuemaster commented
@peermuellerxw Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=1688)!

2021-02-12 21:23 UTC, sothawo requested changes
Thanks for this PR, great work, but I think we should take this further. It is focused on the `NativeSearchQuery`, but I think we should consider the other `Query` implementations here as well.

Something like having a 
```java
public class RescorerQuery {
  Query query; // <-  our Query interface
  ScoreMode scoreMode;
  int windowSize;
}
```
not using Elasticsearch classes here, but also having our own enum for the ScoreMode. This would allow to not only use `NativeSearchQuery` but also for example a `StringQuery`. In the `RequestMapper` this would then be mapped to the corresponding Elasticsearch classes – there are existing methods to convert a `Query` to a `QueryBuilder`.

What do you think about this change?

2021-02-12 21:23 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/core/query/RescorerQuery.java
> +	public RescorerQuery(QueryRescorerBuilder queryRescorerBuilder) {
this is leaking the Elasticsearch class into the API

2021-02-16 08:46 UTC, peermuellerxw commented
Thanks for looking into my PR and for the feedback. Your suggestions do make sense and I am looking to implement them in the following days :)

2021-03-11 01:36 UTC, peermuellerxw commented
I updated the PR and changed the `RescorerQuery` to a "proper" domain object. Let me know if this is what you had in mind and also if you have any other comments/suggestions. @sothawo

2021-03-13 14:51 UTC, sothawo approved these changes
Looks fine, there are just some minor points with null checks. No need for you to fix these, I will do this in a follow-up commit after merging this PR.

2021-03-13 14:51 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/core/RequestFactory.java
> +		QueryRescorerBuilder builder = new QueryRescorerBuilder(Objects.requireNonNull(getQuery(rescorerQuery.getQuery())));
Instead of a `NullPointerException` we should throw an `IllegalArgumentException` here

2021-03-13 14:52 UTC, merged