Add matched_queries fied to SearchHit.
spring-projects/spring-data-elasticsearch pull request #1722
Opened 2021-03-05 19:34 UTC by mdgilene

Closes #1514

- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] There is a ticket in the bug tracker for the project in our [issue tracker](https://github.com/spring-projects/spring-data-elasticsearch/issues).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

2021-03-10 22:28 UTC, sothawo requested changes
Sorry for the delay, just have been looking at this PR and seen that I have not submitted the review, although I did the review when you submitted the PR. I could have sworn I had hit the submit button.

Two minor places: Spring Data baseline is Java 8, so there are two places that need to be changed.

2021-03-10 23:04 UTC, mdgilene commented
Ahh Java 8 vs 9 didn't even cross my mind. Fixed!

2021-03-10 23:05 UTC, mdgilene commented on src/main/java/org/springframework/data/elasticsearch/core/document/DocumentAdapters.java
> +		return List.of(matchedQueries);
Fixed

2021-03-10 23:05 UTC, mdgilene commented on src/test/java/org/springframework/data/elasticsearch/core/DocumentAdaptersUnitTests.java
> +		assertThat(matchedQueries).isEqualTo(List.of("query1", "query2"));
Fixed

2021-03-11 17:31 UTC, sothawo approved these changes

2021-03-11 17:32 UTC, merged

2021-03-11 17:34 UTC, sothawo commented
Thanks again for this PR.