Improve NativeSearchQueryBuilder by adding convenience methods and modifying existing ones.
spring-projects/spring-data-elasticsearch pull request #1855
Opened 2021-07-01 08:04 UTC by xhaggi

Closes #1854

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [issue tracker](https://github.com/spring-projects/spring-data-elasticsearch/issues).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

2021-07-01 08:19 UTC, xhaggi commented
The most important change is the addition of a convenience method to add multiple `SortBuilders` at once. But I then decided, while I was at it, to unify the other methods as well.

2021-07-02 10:59 UTC, sothawo requested changes

2021-07-02 10:59 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/core/query/NativeSearchQueryBuilder.java
> +				highlightFields.toArray(HighlightBuilder.Field[]::new));
This does not compile with Java 8

2021-07-02 11:03 UTC, xhaggi commented on src/main/java/org/springframework/data/elasticsearch/core/query/NativeSearchQueryBuilder.java
> +				highlightFields.toArray(HighlightBuilder.Field[]::new));
Changed.

2021-07-02 13:47 UTC, sothawo approved these changes

2021-07-02 13:47 UTC, merged