Add native support for range field types by using a range object
spring-projects/spring-data-elasticsearch pull request #1863
Opened 2021-07-08 13:04 UTC by xhaggi

Closes #1862. 

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] **There is a ticket in the bug tracker for the project in our [issue tracker](https://github.
  com/spring-projects/spring-data-elasticsearch/issues)**. Add the issue number to the _Closes #issue-number_ line below
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

Closes #issue-number

2021-07-10 18:14 UTC, sothawo requested changes
Nice work; i left a couple of comments.

What do you think about adding default range types like `class IntegerRange extends Range<Integer>{}`?

About the IPs - would be great to have that as well. I'll see if I find something useful

2021-07-10 18:14 UTC, sothawo commented on src/test/java/org/springframework/data/elasticsearch/core/convert/MappingElasticsearchConverterUnitTests.java
> +					.satisfies(e -> {
I learned something new! Did not know about `satisifes`.

2021-07-10 18:14 UTC, sothawo commented on src/test/java/org/springframework/data/elasticsearch/core/convert/MappingElasticsearchConverterUnitTests.java
> +		static final String JSON = "{\"_class\":\"org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverterUnitTests$RangeTests$RangeEntity\",\"integerRange\":{\"lt\":\"1\",\"gt\":\
I'd prefer to have that in a more readable multiline format

2021-07-12 10:14 UTC, xhaggi reviewed
>Nice work; i left a couple of comments.
Thank you, I have addressed your comments.

>What do you think about adding default range types like class IntegerRange extends Range<Integer>{}?
I have no strong opinion on that. Writing Range<Integer> or IntegerRange makes no difference to me.

>About the IPs - would be great to have that as well.
Sure, but IMO we could add it later.

2021-07-12 18:14 UTC, sothawo approved these changes

2021-07-12 18:15 UTC, merged