Move dynamic mapping parameter configuration to @Document and @Field
spring-projects/spring-data-elasticsearch pull request #1872
Opened 2021-07-15 11:49 UTC by xhaggi

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] **There is a ticket in the bug tracker for the project in our [issue tracker](https://github.
  com/spring-projects/spring-data-elasticsearch/issues)**. Add the issue number to the _Closes #issue-number_ line below
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

Closes #1871

2021-07-18 11:02 UTC, sothawo requested changes
some minor remarks, a failing test class

2021-07-18 11:02 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/core/mapping/SimpleElasticsearchPersistentEntity.java
```suggestion
			this.dynamic = document.dynamic();
		} else {
                       this.dynamic = Dynamic.INHERIT;
               }
```

see above

2021-07-18 11:02 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/core/mapping/SimpleElasticsearchPersistentEntity.java
> +	private Dynamic dynamic = Dynamic.INHERIT;
```suggestion
	private final Dynamic dynamic = Dynamic;
```

I'd prefer a `final`property

2021-07-19 08:55 UTC, xhaggi commented on src/main/java/org/springframework/data/elasticsearch/core/index/MappingBuilder.java
> +			builder.field(TYPE_DYNAMIC, parentFieldAnnotation.dynamic().name().toLowerCase());
The method is called twice, for the root and for a nested entity and I thought it was necessary, but it's not. To make both work, I simply removed the "isRootObject" from the "if" statement.

2021-07-20 05:51 UTC, sothawo approved these changes

2021-07-20 05:51 UTC, merged