Add searchAfter interfaces to NativeSearchQueryBuilder
spring-projects/spring-data-elasticsearch pull request #2106
Opened 2022-03-04 12:06 UTC by owen-q

- support searchAfter for nativeSearchQuery

closes https://github.com/spring-projects/spring-data-elasticsearch/issues/2105

2022-03-05 08:51 UTC, sothawo requested changes
We should not use the `SearchAfterIntegrationTests` to test this change. The change is on the `NativeSearchQueryBuilder` and should be tested there. I know there is no test for this builder, but this might be a good opportunity to create it and just test that the `searchAfter` values are set on the `Query` after building it.

2022-03-05 08:51 UTC, sothawo commented on src/test/java/org/springframework/data/elasticsearch/core/paginating/SearchAfterIntegrationTests.java
> +import org.elasticsearch.search.sort.SortOrder;
This pulls in dependencies to Elasticsearch classes in this test, this test is independent of the used query type.

2022-03-12 00:19 UTC, owen-q commented
> We should not use the `SearchAfterIntegrationTests` to test this change. The change is on the `NativeSearchQueryBuilder` and should be tested there. I know there is no test for this builder, but this might be a good opportunity to create it and just test that the `searchAfter` values are set on the `Query` after building it.

@sothawo 
reflect your PR review.
please review again on changes, thank you

2022-03-12 10:27 UTC, sothawo approved these changes

2022-03-12 10:27 UTC, merged