[elc] add support for sorting results by SortOptions to NativeQuery
spring-projects/spring-data-elasticsearch pull request #2264
Opened 2022-08-09 08:55 UTC by xhaggi

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] **There is a ticket in the bug tracker for the project in our [issue tracker](https://github.
  com/spring-projects/spring-data-elasticsearch/issues)**. Add the issue number to the _Closes #issue-number_ line below
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

Closes #2263

2022-08-09 16:40 UTC, sothawo requested changes
some minor remarks

2022-08-09 16:40 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/client/elc/NativeQueryBuilder.java
> +
assert that `fn` is not null

2022-08-10 08:10 UTC, xhaggi commented on src/main/java/org/springframework/data/elasticsearch/client/elc/NativeQueryBuilder.java
> +	public NativeQueryBuilder withSort(List<SortOptions> values) {
I have no strong opinion on this, but the `BaseQueryBuilder` also had a method `withSort` and the `SearchRequest.Builder` has a method called `sort`.

2022-08-10 08:12 UTC, xhaggi commented on src/main/java/org/springframework/data/elasticsearch/client/elc/NativeQueryBuilder.java
> +
Done.

2022-08-10 19:33 UTC, sothawo approved these changes

2022-08-10 19:34 UTC, merged