[elc] add convenient methods to improve access to aggregations
spring-projects/spring-data-elasticsearch pull request #2266
Opened 2022-08-09 09:51 UTC by xhaggi

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] **There is a ticket in the bug tracker for the project in our [issue tracker](https://github.
  com/spring-projects/spring-data-elasticsearch/issues)**. Add the issue number to the _Closes #issue-number_ line below
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

Closes #2265

2022-08-09 17:02 UTC, sothawo requested changes

2022-08-09 17:02 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/client/elc/ElasticsearchAggregations.java
> +		}
```suggestion
		this.aggregationsAsMap = aggregationsAsMap;
```

2022-08-09 17:02 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/client/elc/ElasticsearchAggregations.java
> +		return aggregationsAsMap;
```suggestion
		return Collections.unmodifiableMap(aggregationsAsMap)
```

should be all that's needed

2022-08-10 07:44 UTC, xhaggi commented on src/main/java/org/springframework/data/elasticsearch/client/elc/ElasticsearchAggregations.java
>  	public ElasticsearchAggregations(List<ElasticsearchAggregation> aggregations) {
Ok, then I'll remove it.

2022-08-10 08:04 UTC, xhaggi reviewed
I removed the ctor with the list type and adjusted the code according to your comments.

2022-08-10 19:09 UTC, sothawo approved these changes

2022-08-10 19:10 UTC, merged