Support for SQL.
spring-projects/spring-data-elasticsearch pull request #2949
Opened 2024-07-31 17:05 UTC by youssef3wi

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] **There is a ticket in the bug tracker for the project in our [issue tracker](https://github.com/spring-projects/spring-data-elasticsearch/issues)**. Add the issue number to the _Closes #issue-number_ line below
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

Closes #2683

2024-08-01 11:58 UTC, youssef3wi commented
I should add some test case to verify complex results such as `SELECT SUM(views) FROM x`.

2024-08-03 19:04 UTC, sothawo requested changes
thanks a lot for this; just some minor remarks/questions

2024-08-04 14:57 UTC, sothawo requested changes
doesn't compile 😁

2024-08-04 14:57 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/client/elc/ElasticsearchTemplate.java
> +import static org.springframework.data.elasticsearch.core.sql.types.ResponseFormat.json;
this does not compile, that package does not exist anymore

2024-08-04 14:57 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/client/elc/ReactiveElasticsearchTemplate.java
> +import static org.springframework.data.elasticsearch.core.sql.types.ResponseFormat.json;
this does not compile, that package does not exist anymore

2024-08-04 14:57 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/client/elc/RequestConverter.java
> +					.timeZone(Objects.toString(query.getTimeZone(), null)).format(Objects.toString(query.getFormat(), null));
```suggestion
					.timeZone(Objects.toString(query.getTimeZone(), null)).format("json);
```

2024-08-04 14:57 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/client/elc/ElasticsearchTemplate.java
> +				"The Elasticsearch Java Client only supports JSON format.");
```suggestion
```
nothing to assert here anymore

2024-08-04 14:57 UTC, sothawo commented on src/main/java/org/springframework/data/elasticsearch/client/elc/ReactiveElasticsearchTemplate.java
> +				"The Elasticsearch Java Client only supports JSON format.");
```suggestion
```

2024-08-04 14:57 UTC, sothawo commented on src/test/java/org/springframework/data/elasticsearch/core/sql/SqlOperationsIntegrationTests.java
> +import static org.springframework.data.elasticsearch.core.sql.types.ResponseFormat.yaml;
```suggestion
```

2024-08-04 14:57 UTC, sothawo commented on src/test/java/org/springframework/data/elasticsearch/core/sql/SqlOperationsIntegrationTests.java
> +
```suggestion
```

2024-08-04 14:57 UTC, sothawo commented on src/test/java/org/springframework/data/elasticsearch/core/sql/SqlOperationsIntegrationTests.java
> +	@Test
```suggestion
	@Test // #2683
```

please add the issue number to the tests, overlooked that on the first review

2024-08-06 18:32 UTC, merged