Add count methods to ELC's ReactiveElasticsearchClient.
spring-projects/spring-data-elasticsearch pull request #2985
Opened 2024-10-11 09:43 UTC by maryantocinn

Please let me know if i've missed anything as this is my first time contributing to an open source project.

- Implemented count methods using CountRequest directly with ELC's ReactiveElasticsearchClient, eliminating the need to initialize any entity or repository. 
- Refactored the existing doCount method in ReactiveElasticsearchTemplate to utilize the newly added count method.

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] **There is a ticket in the bug tracker for the project in our [issue tracker](https://github.com/spring-projects/spring-data-elasticsearch/issues)**. Add the issue number to the _Closes #issue-number_ line below
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

Closes #2749

2024-10-13 20:02 UTC, sothawo requested changes
Thanks for your PR to add the `count` method to the `ReactiveElasticsearchClient`, this is all fine for the `ReactiveElasticsearchClient`, but we cannot use this in `org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchTemplate#doCount` - at least not without further investigation.

Why? Originally the `doCount` was implemented with a `CountRequest`( #341), the old one from the previous Elasticsearch libraries. We had to change this to a search query with a size of 0; you find a hint in this old issue: #1290, the count request does not consider the filters set on a query. or the diff in this old commit: https://github.com/spring-projects/spring-data-elasticsearch/commit/2cd18178e3b15bb1c531ef4cd59379a23b735c99#diff-8edbaefd20710bf00d7a492f1d368f3c9efbce5b4628afd4b43a72a8b28af17fL518-R294

Before going to a count request again, it would be necessary to investigate in that and see if it is safe to do this replacement.

But that I'd see in a diferent issue, and have this one just for adding the methods to the `ReactiveElasticsearchClient`.

2024-10-16 06:24 UTC, maryantocinn commented
I see, thank you for the context. I'll leave the investigation of reverting to a `CountRequest` for `ReactiveElasticsearchTemplate#doCount` for a separate issue as it will need a deeper analysis of how the filters work.

For now, I'll revert all the changes made to `ReactiveElasticsearchTemplate` and focus this PR on adding the count methods to the `ReactiveElasticsearchClient` as initially intended.

2024-10-16 06:24 UTC, maryantocinn commented on src/main/java/org/springframework/data/elasticsearch/client/elc/ReactiveElasticsearchTemplate.java
> +		CountRequest request = requestConverter.countRequest(query, entityType, index);
Noted, will remove it.

2024-10-16 06:24 UTC, maryantocinn commented on src/main/java/org/springframework/data/elasticsearch/client/elc/RequestConverter.java
> +				.index(Arrays.asList(indexCoordinates.getIndexNames())));
Thank you for pointing that out. Will look into how the `prepareSearchRequest` works, but for now will remove it as we cannot refactor `doCount` right now.

2024-10-17 15:12 UTC, sothawo approved these changes

2024-10-17 15:13 UTC, merged